PagesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Page-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: Page
        AttributeType: S
      - AttributeName: SiteName
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: title
        AttributeType: S
    KeySchema:
      - AttributeName: Page
        KeyType: HASH
      - AttributeName: SiteName
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    LocalSecondaryIndexes:
      - IndexName: UserPagesIndex
        KeySchema:
          - AttributeName: Page
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: SearchIndex
        KeySchema:
          - AttributeName: Page
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
