PagesBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.PagesBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1

PagesBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    # Bucket: !Ref PagesBucket
    Bucket: ${self:custom.PagesBucket.name}
    PolicyDocument:
      Statement:
        - Sid: AllActions
          Effect: Allow
          Principal: "*"
          Action: "s3:*"
          Resource:
            - arn:aws:s3:::${self:custom.PagesBucket.name}/*
