name: Deploy product-serverless

on:
  push:
    branches:
      - dev

jobs:
  productionDeploy:
    name: production-deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1
      
      - name: Install Serverless Deployment Bucket Plugin
        run: serverless plugin install --name serverless-deployment-bucket
      
      - name: Install Serverless Webpack Plugin
        run: serverless plugin install --name serverless-webpack
      
      - name: Install Serverless IAM Roles per Function Plugin
        run: serverless plugin install --name serverless-iam-roles-per-function
      
      - name: Install Serverless Offline Plugin
        run: serverless plugin install --name serverless-offline
      
      - name: Deploy Serverless Application
        run: serverless deploy --stage dev
