name: Deploy product-serverless

on:
  push:
    branches:
      - dev

jobs:
  productionDeploy:
    name: production-deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
    strategy:
      matrix:
        node-version: "18.x"
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install
      
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1
      
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.2
        with:
          args: "plugin install --name  serverless-deployment-bucket && serverless-webpack && serverless-iam-roles-per-function  && plugin install --name serverless-offline && serverless deploy --stage dev"
        
